[project]
name = "menu-services"
version = "0.1.0"
description = ""
authors = [
    {name = "Héctor Lozada",email = "imatsu@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "flask (>=3.1.1,<4.0.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "alembic (>=1.16.1,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "grpcio (>=1.71.0,<2.0.0)",
    "grpcio-tools (>=1.71.0,<2.0.0)",
    "protobuf (>=6.31.1,<7.0.0)",
    "types-protobuf (>=6.30.2.20250516,<7.0.0.0)",
    "ariadne (>=0.26.2,<0.27.0)",
    "python-jose (>=3.5.0,<4.0.0)",
    "redis (>=6.2.0,<7.0.0)",
    "werkzeug (>=3.1.3,<4.0.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ipython = "^9.2.0"
mypy-protobuf = "^3.6.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
