"""Eliminación lógica

Revision ID: 84ca766c54f9
Revises: ca8afd69b498
Create Date: 2025-06-01 14:11:44.747627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ca766c54f9'
down_revision: Union[str, None] = 'ca8afd69b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('menu_item', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'deleted_at')
    op.drop_column('menu_item', 'is_deleted')
    # ### end Alembic commands ###
